version: 2.1

executors:
  ruby-274:
    working_directory: ~/holistics
    docker:
      - image: cimg/ruby:2.7.4
  node:
    working_directory: ~/holistics
    docker:
      - image: cimg/node:14.19.1

commands:
  bundle_install:
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle install 
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  test-rubocop:
    executor: ruby-274
    steps:
      - checkout
      - bundle_install
      - run:
          command: bundle exec rubocop
  test-rspec:
    executor: ruby-274
    steps:
      - checkout
      - bundle_install
      - run:
          command: bundle exec rspec
      - store_artifacts:
          path: coverage
          destination: coverage
  test-js:
    executor: node
    steps:
      - checkout
      - run:
          command: |
            cd js
            yarn
            yarn test

workflows:
  test-ruby: 
    when: << pipeline.parameters.run_ruby_test >>
    jobs:
      - test-rubocop
      - test-rspec:
          requires:
            - test-rubocop
  test-js: 
    when: << pipeline.parameters.run_js_test >>
    jobs:
      - test-js
