version: 2.1

executors:
  ruby-274:
    working_directory: ~/holistics
    docker:
      - image: cimg/ruby:2.7.4

commands:
  bundle_install:
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle install 
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  test-rubocop:
    executor: ruby-274
    steps:
      - checkout
      - bundle_install
      - run:
          command: bundle exec rubocop
  test-rspec:
    executor: ruby-274
    steps:
      - checkout
      - bundle_install
      - run:
          command: bundle exec rspec

workflows:
  exercise3: 
    jobs:
      - test-rubocop
      - test-rspec:
          requires:
            - test-rubocop
